### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by akihironitta** [pyg-team/pytorch-frame#120]

**Comment by eliazonta** [comment]
Are there some special requirements for the contributing.md file ? 
I would like to contribute to it if possible

**Comment by akihironitta** [comment]
@eliazonta Thank you for showing your interest in contributing :) I think it should look like PyG's CONTRIBUTING.md https://github.com/pyg-team/pytorch_geometric/blob/master/.github/CONTRIBUTING.md where we explain:
- how to set up dev environment
- how to run tests
- how to build docs
