### ISSUE TITLE
feature importance frameworks integration (SHAP, Captum and etc)

### ISSUE THREAD

**Issue by bernardocecchetto** [pyg-team/pytorch-frame#313]
So we can understand the impact of certain features in the model's learning

**Comment by zechengz** [comment]
Yes, we plan to incorporate some XAI such as the Captum, as mentioned in this issue https://github.com/pyg-team/pytorch-frame/issues/282 This module may be added early next year

**Comment by akihironitta** [comment]
Closing this issue in favor of #282.
