### ISSUE TITLE
Try it with custom dataset

### ISSUE THREAD

**Issue by sevimcengiz** [pyg-team/pytorch-frame#322]
Hi all,

I'm ok for all examples. I'm working on a custom dataset. I couldn't manage to implement it usinf torch_frame dataset scripts. I've got an error with DataLoader and using dataset. I tried to write my own custom dataloader but even in the model it uses the outputs which comes from dataset or data loader like dataset.col_stats etc..

How did you handle it and use this nice framework for your custom datasets? Any example or tutorial for custom datasets?

Thanks,

**Comment by weihua916** [comment]
[Here](https://pytorch-frame.readthedocs.io/en/latest/get_started/introduction.html) it is :)
