### ISSUE TITLE
Split dataset by `timestamp`

### ISSUE THREAD

**Issue by xnuohz** [pyg-team/pytorch-frame#335]
In PyF, maybe it's a good choice to add `split_by_col` to split data. Otherwise, need to create split_id by myself.
```
def _add_split(dt: int) -> int:
    if dt <= 20231220:
        return 0
    elif dt <= 20231231:
        return 1
    else:
        return 2
```

**Comment by weihua916** [comment]
In your data frame, you can add a new column (let's say you name it as `date_split`) and then you can pass `split_col = "date_split"`[here](https://github.com/pyg-team/pytorch-frame/blob/master/torch_frame/data/dataset.py#L320-L322).
