### ISSUE TITLE
Support for pyspark dataframe

### ISSUE THREAD

**Issue by saankhya-mondal** [pyg-team/pytorch-frame#348]
Currently, there's support for pandas dataframe. Requesting support for pyspark dataframe.

**Comment by weihua916** [comment]
This is a great and useful suggestion. We will keep this in our roadmap.

**Comment by XinweiHe** [comment]
@saankhya-mondal During the encoding process we will need to load raw data in memory anyway. If we have a pyspark dataframe object, could we just do `df.toPandas()` to convert a pyspark dataframe to a pandas dataframe before using torchframe framework?
