### ISSUE TITLE
About Excelformer

### ISSUE THREAD

**Issue by WhatAShot** [pyg-team/pytorch-frame#387]
Hello, thank you for considering Excelformer. Just a friendly reminder: ExcelFormer utilizes a special initialization methods along with two data augmentation techniques, which might be worth incorporating into the example. Alternatively, you could consider adding a reminder to readers at the beginning of the example file. Thanks!

**Comment by weihua916** [comment]
Thank you for your suggestion! We tried our best to reproduce, but if there is anything significant we missed, do you mind sending us a PR correcting our implementation?

**Comment by WhatAShot** [comment]
I think it is essentially fixed now. Thank you!
