### ISSUE TITLE
Problem in MutualInformationSort

### ISSUE THREAD

**Issue by bernardocecchetto** [pyg-team/pytorch-frame#388]
I have a dataset that was working before, but, after some changes on it, the MutualInformationSort is raising this error, specifically when checking if has any NaNs values. What is this is related to? I really can't understand what it is happening.

![image](https://github.com/pyg-team/pytorch-frame/assets/61297550/bd3b9c68-8960-4a30-8e91-132372cdccb7)

**Comment by bernardocecchetto** [comment]
I already checked if has any NaNs in my dataset, but it does not have

**Comment by akihironitta** [comment]
Have you had a chance to run it with `CUDA_LAUNCH_BLOCKING=1` to see where your script fails? It'd be great if you could provide us with a script to reproduce the error.

**Comment by bernardocecchetto** [comment]
I will debug it with CUDA_LAUNCH_BLOCKING and will provide a return here. Thanks

**Comment by weihua916** [comment]
Hi @bernardocecchetto! Any update on this?

**Comment by bernardocecchetto** [comment]
Sorry for the delay. I was not able see the raw cause of the problem.

I ran the code with `CUDA_LAUNCH_BLOCKING=1`, but does not display any relevant log related to the problem. 

The problem occurs with a specific table that I have, all of the others work fine. But I am not sure what I am missing related to that table, because it does not have any NaNs values, or any other problem on it.

When I run it on cpu, instead of cuda, the problem, then, occurs in CatToNumTransform, raising an error related to index out of range.

**Comment by weihua916** [comment]
Thanks for reporting. I think that's a bug on our side. 
Can you paste the full error when you run on CPU?

**Comment by bernardocecchetto** [comment]
Sure thing, I will paste it here tomorrow.

**Comment by weihua916** [comment]
@bernardocecchetto Let us look at your problem when you get a chance :)

**Comment by bernardocecchetto** [comment]
I am sorry for the delay. This is the problem that raises.


`IndexError                                Traceback (most recent call last)
File <command-1879100230018134>, line 3
      1 train_tensor_frame = categorical_transform(train_tensor_frame)
      2 newdata_tensor_frame = categorical_transform(newdata_tensor_frame)
----> 3 prod_tensor_frame = categorical_transform(prod_tensor_frame)
      5 col_stats = categorical_transform.transformed_stats

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-7b42c0b2-83f7-4ad9-99c3-70b1f461aa1d/lib/python3.10/site-packages/torch_frame/transforms/fittable_base_transform.py:25, in FittableBaseTransform.__call__(self, tf)
     23 def __call__(self, tf: TensorFrame) -> TensorFrame:
     24     # Shallow-copy the data so that we prevent in-place data modification.
---> 25     return self.forward(copy.copy(tf))

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-7b42c0b2-83f7-4ad9-99c3-70b1f461aa1d/lib/python3.10/site-packages/torch_frame/transforms/fittable_base_transform.py:88, in FittableBaseTransform.forward(self, tf)
     83 if not self.is_fitted:
     84     raise ValueError(f"'{self.__class__.__name__}' is not yet fitted ."
     85                      f"Please run `fit()` first before attempting to "
     86                      f"transform the TensorFrame.")
---> 88 transformed_tf = self._forward(tf)
     89 transformed_tf.validate()
     90 return transformed_tf

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-7b42c0b2-83f7-4ad9-99c3-70b1f461aa1d/lib/python3.10/site-packages/torch_frame/transforms/cat_to_num_transform.py:126, in CatToNumTransform._forward(self, tf)
    123     count = torch.tensor(self.col_stats[col_name][StatType.COUNT][1],
    124                          device=tf.device)
    125     feat = tensor[:, i]
--> 126     v = torch.index_select(count, 0, feat).unsqueeze(1).repeat(
    127         1, num_classes - 1)
    128     transformed_tensor[:, i * (num_classes - 1):(i + 1) *
    129                        (num_classes - 1)] = ((v + target_mean) /
    130                                              (self.data_size + 1))
    132 # turn the categorical features into numerical features

IndexError: index out of range in self`


However, I think I know what can be happening. I have a column, during my fit in CatToNumTransform that has a unique value (zero). And I am trying to apply this algorithm fitted in another dataset, that this same column have a binary value (zero and one). This would cause a problem, I suppose. But it is not totally clear with the error message that raises.

**Comment by weihua916** [comment]
Hi @bernardocecchetto, thanks for sharing the stack trace. I think that is expected behavior. We cannot apply `CatToNumTransform` when a new category appears at inference time. Let us add a test case and raise a more informative error message.
