### ISSUE TITLE
Incorrect link in README Implemented Deep Tabular Models section

### ISSUE THREAD

**Issue by Kksk43** [pyg-team/pytorch-frame#405]
Just wanted to point out a small issue in the README file. In the [Implemented Deep Tabular Models](https://github.com/pyg-team/pytorch-frame#implemented-deep-tabular-models) section, the example link for TabTransformer currently points to [https://github.com/pyg-team/pytorch-frame/blob/master/examples/tabtransformer.py](https://github.com/pyg-team/pytorch-frame/blob/master/examples/tabtransformer.py) but it seems to be incorrect (results in a 404).

I think it should probably point to [https://github.com/pyg-team/pytorch-frame/blob/master/examples/tab_transformer.py](https://github.com/pyg-team/pytorch-frame/blob/master/examples/tab_transformer.py).

Would be great if this could be fixed. 

Thanks for your efforts on pytorch-frame – it's a fantastic project!

**Comment by akihironitta** [comment]
Thanks for reporting this issue! Would you be interested in submitting a PR to fix this?
