### ISSUE TITLE
XGBoost did not use the best one iteration to predict

### ISSUE THREAD

**Issue by qychen2001** [pyg-team/pytorch-frame#419]
Very good work!
But when I dug into the details of the implementation, I found a possible bug in your implementation.
From reading the official XGBoost documentation, it is clear that XGBoost.train returns the last iteration of the model, not the best one. More details can be checked [here](https://xgboost.readthedocs.io/en/latest/python/python_intro.html#early-stopping).
Therefore, I think the [code](https://github.com/pyg-team/pytorch-frame/blob/d81b8f7a9e0643fa553d7cb7a1343ef662fd6835/torch_frame/gbdt/tuned_xgboost.py#L175) below may be different from what was actually intended.

```python
boost = xgboost.train(
    self.params,
    dtrain,
    num_boost_round=num_boost_round,
    early_stopping_rounds=50,
    verbose_eval=False,
    evals=[(dvalid, "validation")],
    callbacks=[pruning_callback],
)
pred = boost.predict(dvalid)
```
The predicted code needs to be changed to:
```python
pred = boost.predict(dvalid, iteration_range=(0, boost.best_iteration + 1))
```
Similarly, other places used for prediction will likewise need to be modified.
I'm not sure if my understanding agrees with yours, and if it does, please fix this **as soon as possible**. The existence of this issue can lead to unfair comparisons.

**Comment by yiweny** [comment]
Thank you. this makes sense! We will fix the implementation and rerun experiments
