### ISSUE TITLE
`AttributeError: module 'torch_frame' has no attribute 'multicategorical'`

### ISSUE THREAD

**Issue by ValentinLo62** [pyg-team/pytorch-frame#440]
I get an error when trying to import a Dataset.

```
from torch_frame.data.datasets import Dataset
AttributeError                            Traceback (most recent call last)
[<ipython-input-4-7ffdce4a0332>](https://localhost:8080/#) in <cell line: 1>()
----> 1 from torch_frame.data.datasets import Dataset

1 frames
[/usr/local/lib/python3.10/dist-packages/torch_frame/data/dataset.py](https://localhost:8080/#) in <module>
     42 
     43 COL_TO_PATTERN_STYPE_MAPPING = {
---> 44     "col_to_sep": torch_frame.multicategorical,
     45     "col_to_time_format": torch_frame.timestamp,
     46     "col_to_text_embedder_cfg": torch_frame.text_embedded,

AttributeError: module 'torch_frame' has no attribute 'multicategorical'
```

**Comment by akihironitta** [comment]
Hey @ValentinLo62, thanks for reporting this issue. Can you share what version you use? I cannot reproduce it on `master`.

**Comment by ValentinLo62** [comment]
Hi! Thank You for the mail!I use google colab 
and I load the modules with the following code!pip 
install git+https://github.com/pyg-team/pytorch-frame.git!pip install 
torch_frameimport torchimport torch_frameimport torch.nn.functional as Ffrom torch import 
Tensorfrom tqdm import tqdmVersions:python 3.10.12pytorch_frame 0.2.3torch 2.3.1+cu121torch_frame 1.7.5RegardsValentin-- Будем рады сотрудничеству с Вами!"Агентство Деловых Связей" ООО+375-29/116-49-23 
моб.www.adc.pr.byДобрый день!Суб, 24 Авг 2024 08:21:26 -0700, Akihiro Nitta ***@***.***> писал(а):> Hey 
@ValentinLo62, thanks for reporting this issue. Can you share >what version you use? I cannot reproduce it on `master`.> > --

**Comment by akihironitta** [comment]
`!pip install git+https://github.com/pyg-team/pytorch-frame.git` looks good, but `!pip install torch_frame` is not right as the package `torch-frame` (https://pypi.org/project/torch-frame/) is not managed by us while our PyTorch Frame is https://pypi.org/project/pytorch-frame/.

**Comment by ValentinLo62** [comment]
Thank You very much! It works!Valentin-- 
Будем рады сотрудничеству с Вами!"Агентство Деловых Связей" ООО+375-29/116-49-23 моб.www.adc.pr.byДобрый день!Вск, 25 Авг 
2024 03:41:40 -0700, Akihiro Nitta ***@***.***> писал(а):> `!pip install 
git+https://github.com/pyg-team/pytorch-frame.git` >looks good, but `!pip install torch_frame` is not right as the >package 
`torch-frame` (https://pypi.org/project/torch-frame/) is not >managed by us while our PyTorch Frame is 
>https://pypi.org/project/pytorch-frame/.> > -- > Reply to this email directly or view it on GitHub:> 
https://github.com/pyg-team/pytorch-frame/issues/440#issuecomment-2308774233> You are receiving this because you were mentioned.>
