### ISSUE TITLE
BUG: Target_col count for each category was wrong

### ISSUE THREAD

**Issue by hzm-January** [pyg-team/pytorch-frame#459]
After I converted df to dataset, the target_col count for each category was wrong

`dataset_train = Dataset(dataset_train, col_to_stype=col_to_stype, target_col="label")`

My project is a bit urgent, I hope you can tell me how to fix this error after seeing it, thank you very much.

<img width="955" alt="image" src="https://github.com/user-attachments/assets/eab7ef81-5057-42d7-a5a5-ad34afaff581">

**Comment by hzm-January** [comment]
col_to_stype = {"label": torch_frame.categorical}
type(dataset_train)  is pandas.dataframe

**Comment by hzm-January** [comment]
torch_frame/data/dataset.py

<img width="913" alt="image" src="https://github.com/user-attachments/assets/0f1261b1-be70-40c9-9915-fc93257236a4">

**Comment by akihironitta** [comment]
Would you mind sharing your code and data (or any data) that reproduces the issue?
